# Generated by Django 3.2.6 on 2021-08-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('cod_op', models.IntegerField(unique=True, verbose_name='Codigo de Operador')),
                ('razon', models.CharField(max_length=250, null=True, verbose_name='Razon Social')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('cat_iva', models.IntegerField(blank=True, null=True, verbose_name='Categoria IVA')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('email_dif_pub', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de Difusión Pública')),
                ('email_institucional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Institucional')),
                ('sitioweb', models.URLField(blank=True, max_length=100, null=True, verbose_name='Sitio WEB')),
                ('provincia', models.CharField(blank=True, max_length=90, null=True, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=90, null=True, verbose_name='Localidad')),
                ('cnv_categ', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria de Agente')),
                ('cod_caja_cpd', models.IntegerField(blank=True, null=True, verbose_name='Codigo de CPD CVSA')),
                ('fec_ing_acc', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Accionista')),
                ('fec_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['cod_op'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAgente',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('cod_op', models.IntegerField(db_index=True, verbose_name='Codigo de Operador')),
                ('razon', models.CharField(max_length=250, null=True, verbose_name='Razon Social')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT')),
                ('cat_iva', models.IntegerField(blank=True, null=True, verbose_name='Categoria IVA')),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('email_dif_pub', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de Difusión Pública')),
                ('email_institucional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Institucional')),
                ('sitioweb', models.URLField(blank=True, max_length=100, null=True, verbose_name='Sitio WEB')),
                ('provincia', models.CharField(blank=True, max_length=90, null=True, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=90, null=True, verbose_name='Localidad')),
                ('cnv_categ', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoria de Agente')),
                ('cod_caja_cpd', models.IntegerField(blank=True, null=True, verbose_name='Codigo de CPD CVSA')),
                ('fec_ing_acc', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Accionista')),
                ('fec_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Agente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
